<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TalkToMe.Core\TalkToMe.Core.csproj" />
    <ProjectReference Include="..\TalkToMe.Infrastructure\TalkToMe.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ApplicationIcon>Assets\TalkToMe.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\TalkToMe.ico" />
  </ItemGroup>

</Project>
